taeseokyoung/gwolnadri_front

- assets/js/api.js
- assets/js/login.js
- login.html
assets/api.js : 공용 api.js 추가
assets/login.js : 기본 로그인모델 js 추가
login.html : api.js, login.js import
> [추가] 로그인 연결 #1

- assets/js/store-detail.js
- store-detail.html
assets/store-detail.js : store-detail.html 자바스크립트 추가
store-detail.html : id 추가
> [추가] 한복점 상세페이지 출력 #7

- assets/css/select.css
- assets/js/select_event.js
- assets/js/select_hanbok.js
- event-detail.html
- select.html
select.html : select_hanbok.js / select_event.js 추가
assets/select.css : select.html 스타일 수정
assets/select_event.js : event 결제 추가
assets/select_hanbok.js : select.js > select_hanbok 파일이름 변경
> [추가] 행사 결제 추가 #8

- assets/css/select.css
- assets/js/select.js
- assets/js/select_event.js
- assets/js/select_hanbok.js
- event-detail.html
- select.html
Reverts taeseokyoung/gwolnadri_front#28
> Revert "Feature/payment"

- assets/css/receipt.css
- assets/js/receipt.js
- receipt.html
receipt.html : 결제 상세페이지 추가
assets/receipt.css : 결제 상세페이지 전용 스타일 추가
> [추가] 결제 상세페이지 추가 #31

- assets/js/select_event.js
assets/select_event.js : 잔여좌석 출력문으로 변경
> [수정] 행사 예약시간 출력문 수정 #8

- assets/js/login.js
- assets/js/signup.js
- login.html
- signup.html
-로그인은 백앤드와 연결되었습니다.
-소셜로그인은 연결하는것이 쉽지 않아서, 우선 url연결만 해놨습니다.
-회원가입은 어디서 에러가 나는지 한번 봐주시면 감사하겠습니다. (계속 같은것만 보니 찾기 쉽지 않습니다.)
> [추가] 유저앱 로그인, 회원가입

- assets/js/event.js
- event.html
event.html: 조회내용 출력을 위해 주석처리
event.js: 조회를 위한 js 구현
> [추가] 행사조회 #10

- assets/js/profile.js
- profile.html
- 마이페이지 데이터 불러와서 보이기
- redirect 경로추가 
- 프로필 수정 (유저네임이랑 ">" 클릭시) 
- 나의 관심 행사
- 나의 관심 한복점
- 행사 예약 내역
- 한복점 예약 내역
[해야할것]
- 예약 갯수 가져와서 업데이트하기
- 가입 시 프로필 사진 url 안받아짐 확인하기
- 프로필 업데이트 시 정보 다시 반영하기 필요함 (새로운페이지?)
> feature/userapp [추가] 마이페이지 #5

- assets/css/index.css
- assets/js/api.js
- assets/js/common.js
- assets/js/index.js
- index.html
> [추가] 메인 화면 연결 #15

- assets/css/profile-edit.css
- assets/js/profile-edit.js
- assets/js/profile.js
- profile-edit.html
- profile.html
- signup.html
-프로필 사진 올리기 기능
-유저네임 바꾸기 
(수정 클릭시 아직 반영안됨.) 
-회원탈퇴는 작동함
> [추가] 프로필수정 #3

- assets/css/common.css
- assets/js/common-nonnav.js
- assets/js/store-detail.js
- store-detail.html
23.06.22
assets/css/common.css: 마우스 커서 모양 기본값으로 지정
assets/js/common-nonnav.js : 뒤로가기 추가
assets/js/store-detail.js : 중복 라인 비활성화 | 후기 작성자 노출되게 변경
> [수정] 후기 작성자 추가, 후기 작성 칸 html로 변경 #7

- assets/css/event-detail.css
- assets/css/event.css
- assets/doc/event.html
- assets/js/event.js
- assets/js/event_detail.js
js/event.js: 북마크 유무에 따라 아이콘 이미지 변경, 이벤트 이미지에 커서 기능 추가
js/event_detail.js: 북마크 좋아요 유무에 따라 아이콘 이미지 변경
css/event-detail.css: 삭제하기 버튼 css 수정을 위해 코드 추가 및 수정
css/event-detail.css: 리뷰 컨텐츠 영역을 표시하는 실선 제거
doc/event.html: 더미 데이터 날짜 수정
js/event_detail.js: 삭제하기 버튼 등장 조건 수정
> [수정] 행사 페이지 전반적인 수정 #10 #11

- assets/doc/event.html
- assets/js/event.js
- assets/js/event_detail.js
doc/event.html: 더미 데이터 정보 변경
js/event.js: 백엔드에서 넣은 이미지를 프론트에서 받아 출력하게 수정, 날짜별 reservation 기능 추가
js/event_detail.js: 백엔드에서 넣은 이미지를 프론트에서 받아 출력하게 수정
> [수정] 행사 페이지 기능 수정 #10 #11

- assets/js/event_detail.js
js/event_detail.js: 아이콘 이미지 수정
> [수정] 좋아요 아이콘 수정 #11

- assets/js/event.js
> [수정] 좋아요 아이콘 css변경 #10

- assets/css/profile-bookmark.css
- assets/doc/profile-storeBookmark.html
- assets/js/profile-storebookmark.js
23.06.25
assets/css/profile-bookmark.css : 새로만들 한복점 카드를 위한 css
assets/doc/profile-storeBookmark.html : 기준 div에 Id추가 | 더미데이터 코드 비활성화
assets/js/profile-storebookmark.js : 사용자가 북마크한 한복점 가져오기
> [추가] '나의 관심 한복점' 열람기능 추가 #5

- assets/js/api.js
Reverts taeseokyoung/gwolnadri_front#83
> Revert "Gwolnadri-front v0.2.0"

- assets/js/search.js
> [수정] 좋아요, 북마크 버튼 주석 #77

- assets/css/profile-bookmark.css
- assets/doc/search.html
- assets/js/event.js
- assets/js/event_detail.js
- assets/js/profile-eventBookmark.js
- assets/js/search.js
css/profile-bookmark.css: 좋아요, 북마크 위치 조정
js/profile-eventBookmark.js: 행사 상태 텍스트 추가
js/search.js: 행사 상태 텍스트 추가
js/event.js: 북마크 좋아요 오류 해결
js/event_detail.js: 북마크 좋아요 오류 해결
> [수정] 행사 상태 텍스트 추가 #5 #10 #11 #77

- assets/css/profile-bookmark.css
- assets/doc/profile-storeBookmark.html
- assets/js/profile-storebookmark.js
profile-bookmark.css : icon css 추가
profile-storeBookmark.html : 예외사항 html추가
profile-storebookmark.js : if문 추가
> [추가] 관심 한복점 예외사항처리 #5

- assets/doc/search.html
> [수정] 검색창 여백 #10

- assets/js/index.js
23.06.25
assets/js/index.js : 메인페이지 행사 상세페이지 연결 | 좋아요 갯수 표시 | 북마크 여부에 따라 아이콘 변경
> [수정] 메인페이지 행사 상세페이지 연결, 좋아요 북마크 수정 #15

- assets/js/event.js
- assets/js/profile-eventBookmark.js
- assets/js/search.js
js/event.js: 행사예정 조건에서 행사 시작 7일 전 조건을 제거
js/eventBookmark.js: 행사예정 조건에서 행사 시작 7일 전 조건을 제거
js/search.js: 행사예정 조건에서 행사 시작 7일 전 조건을 제거
조건을 수정하여 행사 시작 전일 때 행사예정을 출력합니다.(7일 전에 대한 조건 삭제)
> [수정] 행사 예정 조건 변경 #5 #10 #77

- assets/css/common.css
- assets/js/loader.js
max-width:1060px 이하부터는 반응형으로 작동합니다.
loder.js : 풋 아이콘 바 좌측 버튼 작동합니다.
> [추가] 반응형 css 적용

- assets/js/event.js
- assets/js/search.js
js/event.js: 좋아요 아이콘 구분, 좋아요 기능 구현
> [수정] 이벤트 리스트에서 좋아요 기능 구현 #10

- assets/doc/home.html
- assets/doc/login.html
- assets/doc/signup.html
home.html : 아이디찾기, 비밀번호 찾기 주석
login.html : 아이디찾기, 비밀번호 찾기, 소셜로그인 주석
signup.html : 이메일 인증 버튼 주석
> [수정] 유저 일부 주석처리 #2

- assets/js/event.js
- assets/js/event_detail.js
- assets/js/profile-eventBookmark.js
- assets/js/search.js
js/event_detail.js: 이미지 src 수정
js/event.js: 이미지 src 수정, 날짜 조건 수정
js/profile-eventBookmar.js:날짜 조건 수정
js/search.js: 날짜 조건 수정
> [수정] 날짜 조건 수정 및 이미지 출력 수정 #10 #11

- assets/css/index.css
- assets/css/profile-bookmark.css
- assets/js/event.js
- assets/js/event_detail.js
- assets/js/index.js
- assets/js/search.js
- index.html
index.html: main-page 주석처리
index.css: 커서 포인트 구현
profile-bookmark.css: 커서 포인트 구현
event_detail.js: 리뷰 작성 시 예외처리 추가
index.js: main-page에 랜덤 함수 추가
> [수정] 배포 전 수정

- assets/css/common.css
- assets/css/home.css
- assets/css/login.css
- assets/css/signup.css
- assets/css/store-detail.css
- assets/css/store.css
- assets/doc/login.html
- assets/doc/store-detail.html
- assets/js/store-detail.js
Changing
- 로그인, 회원가입, 첫 화면 여백 조정
- 한복점 리스트 카드 크기 조정
- 한복점 디테일 페이지 카드 스크롤 수정
> [수정] css 오류 1차 수정

- assets/css/select.css
- assets/doc/select_event.html
- assets/doc/select_hanbok.html
- assets/js/select_event.js
- assets/js/select_hanbok.js
select_event.html : 행사 상세안내 추가, 결제 가격 출력 추가
select_hanbok.html : 한복 안내 추가, 결제 가격 출력 추가
select_event.js : 스크립트 추가
select_hanbok.js : 스크립트 추가
select.css : 스타일 추가
> [추가] 상품 상세안내 추가 #8

- assets/js/search.js
> [수정] 검색 기능 url 수정 #77

- assets/js/store-detail.js
23.07.04
한복점 상세페이지 후기 작성 및 수정 기능 복구
> [수정] 한복점 후기 기능 복구 #7

- assets/doc/home.html
- assets/doc/login.html
> [수정] 카카오 로그인 버튼 이동 #1

- assets/js/event_detail.js
event_detail.js : 티켓오픈 조건문 오류 수정
> [수정] 티켓오픈 버튼 조건문 오류 수정 #11

- assets/doc/select_event.html
- assets/doc/select_hanbok.html
- assets/js/select_event.js
- assets/js/select_hanbok.js
select_event.html : innerText 자리 비움
select_hanbok.html : 위와 같음
select_event.js : fail, cancel url 수정, 오류 경우 처리 수정
select_hanbok.js : 예외 처리 수정
> [수정] 결제 페이지 수정 #8

- assets/js/reservation_detail.js
reservation_detail.js : 예약현황 조건문 추가
> [추가] 예약 현황 상태 추가 #31

- assets/js/api.js
- assets/js/loader.js
api.js : payload, access token, refresh token 삭제 함수 추가
loader.js : CheckEXP 추가 payload 조건문에 실행문 추가
> [추가] 토큰 만료 자동 로그아웃 추가 #1

- assets/doc/event-detail.html
event-detail.html: 2mb 이하 용량의 파일만 업로드 가능합니다 문구 추가
> Feature/230706/피드백수정/style변경 #11

- assets/js/event_detail.js
- assets/js/store-detail.js
23.07.06
assets/js/event_detail.js : 비로그인 사용자 후기 작성시 ' 로그인이 필요합니다' 알림  추가
assets/js/store-detail.js : 비로그인 사용자 후기 작성시 ' 로그인이 필요합니다' 알림  추가
> [수정] 비로그인 사용자 로그인페이지로  리플레이스 #7 #11
